/* eslint-disable */
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Blog Forge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className={` antialiased bg-gray-50 text-gray-900`}
      >
        {children}
      </body>
    </html>
  );
}
